server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  datasource:
    url: ${ECRITIC_DB_URL:jdbc:postgresql://localhost:5433/ecritic}
    username: ${ECRITIC_DB_USERNAME:root}
    password: ${ECRITIC_DB_PASSWORD:root}
  jpa:
    database: POSTGRESQL
  kafka:
    bootstrap-servers: ${ECRITIC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    email-notification-topic: ${ECRITIC_KAFKA_EMAIL_NOTIFICATION_TOPIC:email-notification}
  error:
    include-stacktrace: never
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:af1ce60c0f7}
